---
apiVersion: v1
kind: Secret
metadata:
  name: pece-secrets
  namespace: pece
  labels:
    app: pece
type: Opaque
stringData:
  # Database credentials
  DB_NAME: drupal
  DB_USER: drupal
  DB_PASSWORD: drupal
  DB_ROOT_PASSWORD: password
  DB_HOST: mariadb
  DB_PORT: "3306"
  DB_DRIVER: mysql

  # Drupal admin account
  DRUPAL_ACCOUNT_USERNAME: admin
  DRUPAL_ACCOUNT_PASSWORD: admin
  DRUPAL_ACCOUNT_EMAIL: admin@pece.local

  # N8N credentials
  N8N_CLIENT_ID: c3feec6f-f13b-4288-9979-2e468515edf2
  N8N_CLIENT_SECRET: nfoejhefoi382
  SITE_N8N_USERNAME: n8n
  SITE_N8N_PASSWORD: lsnmsdfoien3r3n3
  N8N_HTTP_ACCESS: "n8n:$apr1$w8Emurar$U8glp9t8jbx1Ciha2Luem/"

  # Project settings
  PROJECT_MAIL: admin@pece.local
  SITE_ADMIN_USERNAME: admin
  SITE_ADMIN_PASSWORD: admin

  # Migrate URL
  MIGRATE_V1_URL: http://v1.pece.local
